### ISSUE TITLE
Validate inserted/updated data conforms to schema

### ISSUE THREAD

**Issue by msolvaag** [msolvaag/redux-db#2]
Inserting a record to a wrong table should be handled somehow.

**Comment by msolvaag** [comment]
I think the minimal implementation of this is to have a "nullable"  or "notNull" definition for the field schema.

**Comment by Martaver** [comment]
I think validation of anything other than referential integrity (if that's what you're planning) should be optional, via a hook, e.g. we're planning to use yup to validate our objects.

Redux-db's problem domain sits quite nicely as dealing with the 'referential' parts of data - and it separates itself quite nicely from the rest. 

My models have denormalized object properties and redux-db works fine with that, since it's oblivious to the individual 'fields' that aren't included in its schema. I think that works very nicely.

**Comment by msolvaag** [comment]
I think you are right. Less is more.
